// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/libros": {
    params: {};
  };
  "/autores": {
    params: {};
  };
  "/genero": {
    params: {};
  };
  "/detalle": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/libros" | "/autores" | "/genero" | "/detalle" | "/users" | "/contact";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_libros.jsx": {
    id: "routes/_libros";
    page: "/libros";
  };
  "routes/_autores.jsx": {
    id: "routes/_autores";
    page: "/autores";
  };
  "routes/_genero.jsx": {
    id: "routes/_genero";
    page: "/genero";
  };
  "routes/_detalle.jsx": {
    id: "routes/_detalle";
    page: "/detalle";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/_libros": typeof import("./app/routes/_libros.jsx");
  "routes/_autores": typeof import("./app/routes/_autores.jsx");
  "routes/_genero": typeof import("./app/routes/_genero.jsx");
  "routes/_detalle": typeof import("./app/routes/_detalle.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
};